### ISSUE TITLE
Create database for the notes, and passing data to recyclerview

### ISSUE THREAD

**Issue by osazeimohe** [AndroidGrp9Codepath/EverythingCollege#7]

**Comment by yunsanch** [comment]
i created the DB for the notes however something is going on that i cant get the fragment to display any info.

**Comment by yunsanch** [comment]
this is created and the application shows all of the entries put in the app @Shankarmagar was able to find out that the problem was that i was not referring to the main activity, once the id was assigned and used, it all work properly
